# Generated by Django 6.0.4 on 2026-07-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presidentialquote',
            old_name='source_label',
            new_name='source_title',
        ),
        migrations.AddField(
            model_name='presidentialquote',
            name='source_date',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
