# Generated by Django 6.0.4 on 2026-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_source_label_presidentialquote_source_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystats',
            name='president_name',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='facultystats',
            name='president_photo_fallback',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='facultystats',
            name='president_title',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
