# Generated by Django 6.0.4 on 2026-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_president_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Aloqa maʼlumoti', 'verbose_name_plural': 'Aloqa (kontakt)'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['slug'], 'verbose_name': 'Kafedra', 'verbose_name_plural': 'Kafedralar'},
        ),
        migrations.AlterModelOptions(
            name='facultystats',
            options={'verbose_name': 'Fakultet statistikasi', 'verbose_name_plural': 'Statistika va faktlar'},
        ),
        migrations.AlterModelOptions(
            name='heroslide',
            options={'ordering': ['sort_order'], 'verbose_name': 'Hero slayd', 'verbose_name_plural': 'Hero slaydlar (bosh sahifa)'},
        ),
        migrations.AlterModelOptions(
            name='historyevent',
            options={'ordering': ['sort_order', 'year'], 'verbose_name': 'Tarixiy voqea', 'verbose_name_plural': 'Fakultet tarixi'},
        ),
        migrations.AlterModelOptions(
            name='navoibandquote',
            options={'ordering': ['page_key'], 'verbose_name': 'Navoiy merosi (sahifa oxiri)', 'verbose_name_plural': 'Navoiy merosi lentasi'},
        ),
        migrations.AlterModelOptions(
            name='navoiquote',
            options={'ordering': ['sort_order'], 'verbose_name': 'Navoiy iqtibos (landing)', 'verbose_name_plural': 'Navoiy iqtiboslar (landing)'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Hamkor', 'verbose_name_plural': 'Xalqaro hamkorlar'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['sort_order', 'slug'], 'verbose_name': 'Shaxs', 'verbose_name_plural': 'Shaxslar (rahbar, professor, talaba)'},
        ),
        migrations.AlterModelOptions(
            name='presidentialquote',
            options={'ordering': ['sort_order'], 'verbose_name': 'Prezident iqtibosi', 'verbose_name_plural': 'Prezident iqtiboslari'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['level', 'slug'], 'verbose_name': "Ta'lim yo'nalishi", 'verbose_name_plural': "Ta'lim yo'nalishlari"},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['slug'], 'verbose_name': 'Ilmiy loyiha', 'verbose_name_plural': 'Ilmiy loyihalar'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'id'], 'verbose_name': 'Nashr', 'verbose_name_plural': 'Nashrlar (maqola, monografiya)'},
        ),
        migrations.AlterModelOptions(
            name='rectoraddress',
            options={'verbose_name': 'Rektor murojaati', 'verbose_name_plural': 'Rektor murojaati'},
        ),
        migrations.AlterModelOptions(
            name='tutoractivity',
            options={'ordering': ['-date'], 'verbose_name': 'Tyutor faoliyati', 'verbose_name_plural': 'Tyutor faoliyatlari'},
        ),
        migrations.AlterModelOptions(
            name='tutorgroup',
            options={'ordering': ['slug'], 'verbose_name': 'Tyutor guruhi', 'verbose_name_plural': 'Tyutor guruhlari'},
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='hero/%Y/%m/', verbose_name='Rasm yuklash (media)'),
        ),
        migrations.AddField(
            model_name='news',
            name='cover_file',
            field=models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='Muqova yuklash (media)'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/', verbose_name='Logo yuklash'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_file',
            field=models.ImageField(blank=True, help_text='Yuklansa, saytda shu rasm ko‘rsatiladi (URL dan ustun)', null=True, upload_to='people/%Y/%m/', verbose_name='Rasm yuklash (media)'),
        ),
        migrations.AddField(
            model_name='presidentialquote',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='president/%Y/%m/', verbose_name='Rasm yuklash'),
        ),
        migrations.AddField(
            model_name='rectoraddress',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='rector/%Y/%m/', verbose_name='Rasm yuklash'),
        ),
        migrations.AddField(
            model_name='tutoractivity',
            name='photo_file',
            field=models.ImageField(blank=True, null=True, upload_to='activities/%Y/%m/', verbose_name='Rasm yuklash'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rasm URL (internet)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.CharField(blank=True, max_length=500, verbose_name='Muqova URL (internet)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.CharField(blank=True, help_text='Ixtiyoriy: https://... yoki /images/... — media yuklanmagan bo‘lsa ishlatiladi', max_length=500, verbose_name='Rasm URL (internet)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles',
            field=models.JSONField(default=list, help_text='Rollar: leader, professor, tutor, student, honorary'),
        ),
        migrations.AlterField(
            model_name='presidentialquote',
            name='photo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='rectoraddress',
            name='photo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='tutoractivity',
            name='photo',
            field=models.CharField(blank=True, max_length=500, verbose_name='Rasm URL'),
        ),
    ]
